CREATE TABLE cursos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    activo BIT(1) NOT NULL,
    categoria ENUM('MATEMATICA', 'LENGUA', 'FISICA', 'QUIMICA', 'LEYES') NOT NULL,
    name VARCHAR(255) NOT NULL
);